[package]
name = "setup-wp"
version = "0.1.0"
authors = ["Jascha030 <contact@jaschavanaalst.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
